using Core.Entities;
using Core.Repositories.Query.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Repositories.Query
{
    public interface IEmailTopicsQueryRepository
    {
        //Custom operation which is not generic
        Task<IReadOnlyList<EmailTopics>> GetAllAsync();
        Task<IReadOnlyList<EmailTopics>> GetAllEmailTopicsAsync(long UserId);
        Task<IReadOnlyList<EmailCopyLink>> GetConversationList(long ConversationID);
        EmailActivityCatgorys GetUserAsync(string? Usertag);
        Task<IReadOnlyList<TransferEmailHistory>> GetEmailHistoryList(long ID);
         Task<List<EmailTopics>> GetByIdAsync(Int64 id);             
        Task<List<EmailTopics>> GetUserTopicList(Int64 UserId);
        Task<List<RequestEmail>> RequestEmailToCCList(Int64 ConId);
        Task<List<RequestEmail>> RequestEmailParticipantList(Int64 conversationID);
        Task<List<RequestEmail>> RequestEmailToOnlyList(Int64 ConId);
        Task<List<EmailTopics>> GetBySessionTopicList(string SessionId);
        Task<List<EmailTopics>> GetByIdTopicListAsync(Int64 id);
        Task<List<EmailTopics>> GetByIdTopicToList(Int64 UserId);
        Task<List<EmailTopics>> GetByCopyEmailList(long ID);
        Task<List<EmailTopics>> GetByIdTopicCCList(Int64 UserId);
        Task<List<long>> GetByIdUserGroupToList(Int64 UserId);
        Task<List<long>> GetByIdUserGroupCCList(Int64 UserId);
        Task<List<EmailTopics>> GetTopicToList(Int64 UserId,string SearchTxt, int pageNumber, int pageSize);
        Task<List<EmailTopics>> GetTopicTransferList(Int64 UserId, string SearchTxt, int pageNumber, int pageSize);
        Task<List<EmailTopics>> GetTopicToSearchList(string SearchTxt ,Int64 UserId);        
        Task<long> SetPinTopicToList(Int64 Id, long UserId); 
        Task<long> UnSetPinTopicToList(Int64 Id, long UserId);
        Task<long> UpdateMarkasReadList(Int64 Id);
        Task<long> UpdateMarkasAllReadList(Int64 Id,long userId);
        Task<long> UpdateMarkasunReadList(Int64 Id);
        Task<List<EmailTopics>> GetTopicAllList(Int64 UserId,string SearchTxt, int pageNumber, int pageSize);
        Task<List<EmailTopics>> GetTopicFilterList(Int64 UserId,Guid sessionId);
        Task<List<EmailTopics>> GetTopicHomeList(Int64 UserId);
        Task<List<EmailTopics>> GetTopicMasterSearchList(EmailSearch emailSearch);
        Task<List<EmailTopics>> GetTopicAdminSearchList(EmailSearch emailSearch);        
        Task<List<EmailTopics>> GetTopicCCList(Int64 UserId,string SearchTxt);
        Task<List<EmailTopics>> GetTopicDraftList(Int64 UserId);
        long DeleteTopicDraftList(Int64 TopicId);
        Task<List<EmailTopics>> GetSubTopicToList(Int64 TopicId,long UserId,string SearchTxt);
        Task<List<EmailTopics>> GetSubTopicSearchAllList(Int64 TopicId, long UserId,string SearchTxt);        
        Task<List<EmailTopics>> GetSubTopicCCList(Int64 TopicId, long UserId, string SearchTxt);
        Task<List<EmailTopics>> GetSubTopicSentList(Int64 TopicId, long UserId, string SearchTxt);
        Task<List<EmailTopics>> GetSubTopicAllList(Int64 TopicId, long UserId, string SearchTxt);
        Task<List<EmailTopics>> GetSubAdminEmailTopicAllList(Int64 TopicId, long UserId, string SearchTxt);
        Task<List<EmailTopics>> GetSubTopicHomeList(Int64 TopicId, long UserId);
        Task<List<EmailTopics>> GetTopicSentList(Int64 UserId,string searchTxt);
        Task<List<EmailParticipant>> GetParticipantList(Int64 topicId,long UserId);
        Task<List<EmailConversationAssignToUserGroup>> GetGroupParticipantList(Int64 topicId, long UserId);        
        Task<List<EmailParticipant>> GetConversationPList(Int64 ConversationId);
        Task<List<EmailConversationAssignToUserGroup>> GetConversationGroupPList(Int64 ConversationId);
        Task<List<EmailParticipant>> GetParticipantbysessionidList(Guid sessionId);
        Task<EmailTopics> GetCustomerByEmail(string email);
        long Insert(EmailTopics EmailTopics);
        long EmailTopicUpdate(EmailTopics EmailTopics);
        long Insert_sp_Participant(TopicParticipant topicParticipant);
        Task<long> InsertParticipant(TopicParticipant topicParticipant);
        Task<EmailTopics> GetTopicListAsync();
        Task<List<EmailDueDateHistory>> GetEmailDueDateHistoryList(long id);
        Task<long> UpdateDueDate(EmailTopics EmailTopics);      
        Task<List<EmailNotifyPA>> GetNotifyPAAsync(string? Type);
        Task<EmailNotifyPA> GetByIdNotifyPAAsync(Guid sessionId,string Type);
        Task<EmailNotifyPA> GetByIdNotifyPAPrintAsync(Guid sessionId);
        Task<long> CreateNotifyPAAsync(EmailNotifyPA emailNotifyPA);
        Task<long> UpdateNotifyPAAsync(EmailNotifyPA emailNotifyPA);
        Task<long> UpdateCommentNotifyPAAsync(EmailNotifyPA emailNotifyPA);
        Task<long> CreateUserTagAsync(EmailActivityCatgorys emailActivityCatgorys);        
        Task<long> UpdateUserTagAsync(EmailActivityCatgorys emailActivityCatgorys);
        Task<long> InsertEmailDueDateHistory(EmailConversations emailConversations);
        Task<long> CreateEmailTimelineEventAsync(EmailTimelineEvent emailTimelineEvent);
        Task<long> UpdateEmailTimelineEventAsync(EmailTimelineEvent emailTimelineEvent);
        Task<List<EmailTimelineEvent>> GetEmailTimelineEvent(long DocumentId);
        Task<long> UpdateSubjectDueDate(EmailConversations emailConversations);
        Task<long> UpdateSubjectName(EmailConversations emailConversations);
        Task<long> UpdateTopicClose(EmailTopics EmailTopics);
        Task<long> UpdateTopicArchive(EmailTopics emailTopics);
        Task<long> UpdateTopicGroupArchive(EmailTopics emailTopics);
        Task<long> UpdateTopicUnArchive(EmailTopics emailTopics);
        Task<List<ActivityEmailTopics>> GetByActivityEmailSessionList(Guid sessionId);
        Task<List<ActivityEmailTopics>> GetActivityEmailListBySession(Guid sessionId);
        Task<List<ActivityEmailTopics>> GetActivityEmailDocListBySession(Guid sessionId);
        Task<List<Documents>> GetCreateEmailDocumentListAsync(Guid sessionId);
        Task<List<Documents>> GetDynamicFormDocumentListAsync(Guid sessionId);
        Task<List<DynamicFormSection>> GetDynamicFormEmailSectionListAsync(Guid sessionid);
        Task<List<DynamicFormSectionSecurity>> GetUserListByDynamicFormAsync(long id);        
        Task<List<DynamicFormData>> GetDynamicFormNameAsync(Guid sessionId);
        Task<List<Documents>> GetPATypeDocLstAsync(long Id,string Type);        
        Task<long> CreateActivityEmailAsync(ActivityEmailTopics activityEmailTopics);
        Task<long> UpdateActivityEmailAsync(ActivityEmailTopics activityEmailTopics);
        Task<EmailTopics?> CheckEmailSubjectAsync(string subjectName);
        Task<long> Delete(long id);
        Task<long> DeleteNotify(long id);   
        Task<long> InsertUserTagMultiple(EmailActivityCatgorys emailActivityCatgorys);
        Task<IReadOnlyList<Documents>> GetDynamicFormDataDynamicFormDataUploadList(Guid? SessionIds);
        Task<long> InsertTransferHistory(TransferEmailHistory transferEmailHistory);
    }
}
