//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWWebIntegration
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", ConfigurationName="SWWebIntegration.WebIntegration_Port")]
    public interface WebIntegration_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnInitNewRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnInitNewRecords_Result> FnInitNewRecordsAsync(SWWebIntegration.FnInitNewRecords request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateInventory_Result> FnCalculateInventoryAsync(SWWebIntegration.FnCalculateInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateFMInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateFMInventory_Result> FnCalculateFMInventoryAsync(SWWebIntegration.FnCalculateFMInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateAdhocInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateAdhocInventory_Result> FnCalculateAdhocInventoryAsync(SWWebIntegration.FnCalculateAdhocInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateRWInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateRWInventory_Result> FnCalculateRWInventoryAsync(SWWebIntegration.FnCalculateRWInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateWIPInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateWIPInventory_Result> FnCalculateWIPInventoryAsync(SWWebIntegration.FnCalculateWIPInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalcNotStartInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalcNotStartInventory_Result> FnCalcNotStartInventoryAsync(SWWebIntegration.FnCalcNotStartInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnUpdateStartDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnUpdateStartDate_Result> FnUpdateStartDateAsync(SWWebIntegration.FnUpdateStartDate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnUpdateStartDatebyLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnUpdateStartDatebyLine_Result> FnUpdateStartDatebyLineAsync(SWWebIntegration.FnUpdateStartDatebyLine request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateSupplyWIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateSupplyWIP_Result> FnCalculateSupplyWIPAsync(SWWebIntegration.FnCalculateSupplyWIP request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnCalculateSupply1stProces" +
            "s", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateSupply1stProcess_Result> FnCalculateSupply1stProcessAsync(SWWebIntegration.FnCalculateSupply1stProcess request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebIntegration:FnUpdateCompleteOrderbyLin" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWWebIntegration.FnUpdateCompleteOrderbyLine_Result> FnUpdateCompleteOrderbyLineAsync(SWWebIntegration.FnUpdateCompleteOrderbyLine request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnInitNewRecords", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnInitNewRecords
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnInitNewRecords()
        {
        }
        
        public FnInitNewRecords(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnInitNewRecords_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnInitNewRecords_Result
    {
        
        public FnInitNewRecords_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateInventory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateInventory()
        {
        }
        
        public FnCalculateInventory(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateInventory_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateInventory_Result()
        {
        }
        
        public FnCalculateInventory_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateFMInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateFMInventory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateFMInventory()
        {
        }
        
        public FnCalculateFMInventory(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateFMInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateFMInventory_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateFMInventory_Result()
        {
        }
        
        public FnCalculateFMInventory_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateAdhocInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateAdhocInventory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateAdhocInventory()
        {
        }
        
        public FnCalculateAdhocInventory(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateAdhocInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateAdhocInventory_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateAdhocInventory_Result()
        {
        }
        
        public FnCalculateAdhocInventory_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateRWInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateRWInventory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateRWInventory()
        {
        }
        
        public FnCalculateRWInventory(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateRWInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateRWInventory_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateRWInventory_Result()
        {
        }
        
        public FnCalculateRWInventory_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateWIPInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateWIPInventory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateWIPInventory()
        {
        }
        
        public FnCalculateWIPInventory(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateWIPInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateWIPInventory_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateWIPInventory_Result()
        {
        }
        
        public FnCalculateWIPInventory_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalcNotStartInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalcNotStartInventory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalcNotStartInventory()
        {
        }
        
        public FnCalcNotStartInventory(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalcNotStartInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalcNotStartInventory_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalcNotStartInventory_Result()
        {
        }
        
        public FnCalcNotStartInventory_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateStartDate", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnUpdateStartDate
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeReplanRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteActualStart;
        
        public FnUpdateStartDate()
        {
        }
        
        public FnUpdateStartDate(string p_cdeReplanRefNo, System.DateTime p_dteActualStart)
        {
            this.p_cdeReplanRefNo = p_cdeReplanRefNo;
            this.p_dteActualStart = p_dteActualStart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateStartDate_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnUpdateStartDate_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string return_value;
        
        public FnUpdateStartDate_Result()
        {
        }
        
        public FnUpdateStartDate_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateStartDatebyLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnUpdateStartDatebyLine
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeProdOrderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        public int p_intLineNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteActualStart;
        
        public FnUpdateStartDatebyLine()
        {
        }
        
        public FnUpdateStartDatebyLine(string p_cdeProdOrderNo, int p_intLineNo, System.DateTime p_dteActualStart)
        {
            this.p_cdeProdOrderNo = p_cdeProdOrderNo;
            this.p_intLineNo = p_intLineNo;
            this.p_dteActualStart = p_dteActualStart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateStartDatebyLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnUpdateStartDatebyLine_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime return_value;
        
        public FnUpdateStartDatebyLine_Result()
        {
        }
        
        public FnUpdateStartDatebyLine_Result(System.DateTime return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateSupplyWIP", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateSupplyWIP
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateSupplyWIP()
        {
        }
        
        public FnCalculateSupplyWIP(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateSupplyWIP_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateSupplyWIP_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateSupplyWIP_Result()
        {
        }
        
        public FnCalculateSupplyWIP_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateSupply1stProcess", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateSupply1stProcess
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeItemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime p_dteAsOfDate;
        
        public FnCalculateSupply1stProcess()
        {
        }
        
        public FnCalculateSupply1stProcess(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            this.p_cdeItemNo = p_cdeItemNo;
            this.p_dteAsOfDate = p_dteAsOfDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCalculateSupply1stProcess_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnCalculateSupply1stProcess_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public decimal return_value;
        
        public FnCalculateSupply1stProcess_Result()
        {
        }
        
        public FnCalculateSupply1stProcess_Result(decimal return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateCompleteOrderbyLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnUpdateCompleteOrderbyLine
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public string p_cdeProdOrderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=1)]
        public int p_intLineNo;
        
        public FnUpdateCompleteOrderbyLine()
        {
        }
        
        public FnUpdateCompleteOrderbyLine(string p_cdeProdOrderNo, int p_intLineNo)
        {
            this.p_cdeProdOrderNo = p_cdeProdOrderNo;
            this.p_intLineNo = p_intLineNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateCompleteOrderbyLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", IsWrapped=true)]
    public partial class FnUpdateCompleteOrderbyLine_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebIntegration", Order=0)]
        public bool return_value;
        
        public FnUpdateCompleteOrderbyLine_Result()
        {
        }
        
        public FnUpdateCompleteOrderbyLine_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebIntegration_PortChannel : SWWebIntegration.WebIntegration_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebIntegration_PortClient : System.ServiceModel.ClientBase<SWWebIntegration.WebIntegration_Port>, SWWebIntegration.WebIntegration_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebIntegration_PortClient() : 
                base(WebIntegration_PortClient.GetDefaultBinding(), WebIntegration_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WebIntegration_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebIntegration_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(WebIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), WebIntegration_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebIntegration_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebIntegration_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebIntegration_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnInitNewRecords_Result> SWWebIntegration.WebIntegration_Port.FnInitNewRecordsAsync(SWWebIntegration.FnInitNewRecords request)
        {
            return base.Channel.FnInitNewRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnInitNewRecords_Result> FnInitNewRecordsAsync(int p_intEntryNo)
        {
            SWWebIntegration.FnInitNewRecords inValue = new SWWebIntegration.FnInitNewRecords();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnInitNewRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateInventory_Result> SWWebIntegration.WebIntegration_Port.FnCalculateInventoryAsync(SWWebIntegration.FnCalculateInventory request)
        {
            return base.Channel.FnCalculateInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateInventory_Result> FnCalculateInventoryAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateInventory inValue = new SWWebIntegration.FnCalculateInventory();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateFMInventory_Result> SWWebIntegration.WebIntegration_Port.FnCalculateFMInventoryAsync(SWWebIntegration.FnCalculateFMInventory request)
        {
            return base.Channel.FnCalculateFMInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateFMInventory_Result> FnCalculateFMInventoryAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateFMInventory inValue = new SWWebIntegration.FnCalculateFMInventory();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateFMInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateAdhocInventory_Result> SWWebIntegration.WebIntegration_Port.FnCalculateAdhocInventoryAsync(SWWebIntegration.FnCalculateAdhocInventory request)
        {
            return base.Channel.FnCalculateAdhocInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateAdhocInventory_Result> FnCalculateAdhocInventoryAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateAdhocInventory inValue = new SWWebIntegration.FnCalculateAdhocInventory();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateAdhocInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateRWInventory_Result> SWWebIntegration.WebIntegration_Port.FnCalculateRWInventoryAsync(SWWebIntegration.FnCalculateRWInventory request)
        {
            return base.Channel.FnCalculateRWInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateRWInventory_Result> FnCalculateRWInventoryAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateRWInventory inValue = new SWWebIntegration.FnCalculateRWInventory();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateRWInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateWIPInventory_Result> SWWebIntegration.WebIntegration_Port.FnCalculateWIPInventoryAsync(SWWebIntegration.FnCalculateWIPInventory request)
        {
            return base.Channel.FnCalculateWIPInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateWIPInventory_Result> FnCalculateWIPInventoryAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateWIPInventory inValue = new SWWebIntegration.FnCalculateWIPInventory();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateWIPInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalcNotStartInventory_Result> SWWebIntegration.WebIntegration_Port.FnCalcNotStartInventoryAsync(SWWebIntegration.FnCalcNotStartInventory request)
        {
            return base.Channel.FnCalcNotStartInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalcNotStartInventory_Result> FnCalcNotStartInventoryAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalcNotStartInventory inValue = new SWWebIntegration.FnCalcNotStartInventory();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalcNotStartInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnUpdateStartDate_Result> SWWebIntegration.WebIntegration_Port.FnUpdateStartDateAsync(SWWebIntegration.FnUpdateStartDate request)
        {
            return base.Channel.FnUpdateStartDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnUpdateStartDate_Result> FnUpdateStartDateAsync(string p_cdeReplanRefNo, System.DateTime p_dteActualStart)
        {
            SWWebIntegration.FnUpdateStartDate inValue = new SWWebIntegration.FnUpdateStartDate();
            inValue.p_cdeReplanRefNo = p_cdeReplanRefNo;
            inValue.p_dteActualStart = p_dteActualStart;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnUpdateStartDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnUpdateStartDatebyLine_Result> SWWebIntegration.WebIntegration_Port.FnUpdateStartDatebyLineAsync(SWWebIntegration.FnUpdateStartDatebyLine request)
        {
            return base.Channel.FnUpdateStartDatebyLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnUpdateStartDatebyLine_Result> FnUpdateStartDatebyLineAsync(string p_cdeProdOrderNo, int p_intLineNo, System.DateTime p_dteActualStart)
        {
            SWWebIntegration.FnUpdateStartDatebyLine inValue = new SWWebIntegration.FnUpdateStartDatebyLine();
            inValue.p_cdeProdOrderNo = p_cdeProdOrderNo;
            inValue.p_intLineNo = p_intLineNo;
            inValue.p_dteActualStart = p_dteActualStart;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnUpdateStartDatebyLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateSupplyWIP_Result> SWWebIntegration.WebIntegration_Port.FnCalculateSupplyWIPAsync(SWWebIntegration.FnCalculateSupplyWIP request)
        {
            return base.Channel.FnCalculateSupplyWIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateSupplyWIP_Result> FnCalculateSupplyWIPAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateSupplyWIP inValue = new SWWebIntegration.FnCalculateSupplyWIP();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateSupplyWIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnCalculateSupply1stProcess_Result> SWWebIntegration.WebIntegration_Port.FnCalculateSupply1stProcessAsync(SWWebIntegration.FnCalculateSupply1stProcess request)
        {
            return base.Channel.FnCalculateSupply1stProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnCalculateSupply1stProcess_Result> FnCalculateSupply1stProcessAsync(string p_cdeItemNo, System.DateTime p_dteAsOfDate)
        {
            SWWebIntegration.FnCalculateSupply1stProcess inValue = new SWWebIntegration.FnCalculateSupply1stProcess();
            inValue.p_cdeItemNo = p_cdeItemNo;
            inValue.p_dteAsOfDate = p_dteAsOfDate;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnCalculateSupply1stProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWWebIntegration.FnUpdateCompleteOrderbyLine_Result> SWWebIntegration.WebIntegration_Port.FnUpdateCompleteOrderbyLineAsync(SWWebIntegration.FnUpdateCompleteOrderbyLine request)
        {
            return base.Channel.FnUpdateCompleteOrderbyLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWWebIntegration.FnUpdateCompleteOrderbyLine_Result> FnUpdateCompleteOrderbyLineAsync(string p_cdeProdOrderNo, int p_intLineNo)
        {
            SWWebIntegration.FnUpdateCompleteOrderbyLine inValue = new SWWebIntegration.FnUpdateCompleteOrderbyLine();
            inValue.p_cdeProdOrderNo = p_cdeProdOrderNo;
            inValue.p_intLineNo = p_intLineNo;
            return ((SWWebIntegration.WebIntegration_Port)(this)).FnUpdateCompleteOrderbyLineAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebIntegration_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                result.Security.Transport.ProxyCredentialType = System.ServiceModel.HttpProxyCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebIntegration_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://jbnav.sunwardpharma.com:7547/DynamicsNAV100/WS/SWMY LIVE/Codeunit/WebInteg" +
                        "ration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebIntegration_PortClient.GetBindingForEndpoint(EndpointConfiguration.WebIntegration_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebIntegration_PortClient.GetEndpointAddress(EndpointConfiguration.WebIntegration_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            WebIntegration_Port,
        }
    }
}
