//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSoapService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", ConfigurationName="SWSoapService.SWDWebIntegration_Port")]
    public interface SWDWebIntegration_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnUpdatePurchaseReceive" +
            "Line", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnUpdatePurchaseReceiveLine_Result> FnUpdatePurchaseReceiveLineAsync(SWSoapService.FnUpdatePurchaseReceiveLine request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnPostPurchaseReceive", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnPostPurchaseReceive_Result> FnPostPurchaseReceiveAsync(SWSoapService.FnPostPurchaseReceive request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnCreateSalesOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnCreateSalesOrder_Result> FnCreateSalesOrderAsync(SWSoapService.FnCreateSalesOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnPostSalesShipment", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnPostSalesShipment_Result> FnPostSalesShipmentAsync(SWSoapService.FnPostSalesShipment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnPostSalesInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnPostSalesInvoice_Result> FnPostSalesInvoiceAsync(SWSoapService.FnPostSalesInvoice request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnPostItemJournal", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnPostItemJournal_Result> FnPostItemJournalAsync(SWSoapService.FnPostItemJournal request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration:FnPostQCInspection", ReplyAction="*")]
        System.Threading.Tasks.Task<SWSoapService.FnPostQCInspection_Result> FnPostQCInspectionAsync(SWSoapService.FnPostQCInspection request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdatePurchaseReceiveLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnUpdatePurchaseReceiveLine
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnUpdatePurchaseReceiveLine()
        {
        }
        
        public FnUpdatePurchaseReceiveLine(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdatePurchaseReceiveLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnUpdatePurchaseReceiveLine_Result
    {
        
        public FnUpdatePurchaseReceiveLine_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostPurchaseReceive", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostPurchaseReceive
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnPostPurchaseReceive()
        {
        }
        
        public FnPostPurchaseReceive(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostPurchaseReceive_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostPurchaseReceive_Result
    {
        
        public FnPostPurchaseReceive_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCreateSalesOrder", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnCreateSalesOrder
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnCreateSalesOrder()
        {
        }
        
        public FnCreateSalesOrder(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCreateSalesOrder_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnCreateSalesOrder_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public string return_value;
        
        public FnCreateSalesOrder_Result()
        {
        }
        
        public FnCreateSalesOrder_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostSalesShipment", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostSalesShipment
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnPostSalesShipment()
        {
        }
        
        public FnPostSalesShipment(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostSalesShipment_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostSalesShipment_Result
    {
        
        public FnPostSalesShipment_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostSalesInvoice", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostSalesInvoice
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnPostSalesInvoice()
        {
        }
        
        public FnPostSalesInvoice(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostSalesInvoice_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostSalesInvoice_Result
    {
        
        public FnPostSalesInvoice_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostItemJournal", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostItemJournal
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnPostItemJournal()
        {
        }
        
        public FnPostItemJournal(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostItemJournal_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostItemJournal_Result
    {
        
        public FnPostItemJournal_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostQCInspection", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostQCInspection
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", Order=0)]
        public int p_intEntryNo;
        
        public FnPostQCInspection()
        {
        }
        
        public FnPostQCInspection(int p_intEntryNo)
        {
            this.p_intEntryNo = p_intEntryNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnPostQCInspection_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SWDWebIntegration", IsWrapped=true)]
    public partial class FnPostQCInspection_Result
    {
        
        public FnPostQCInspection_Result()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SWDWebIntegration_PortChannel : SWSoapService.SWDWebIntegration_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SWDWebIntegration_PortClient : System.ServiceModel.ClientBase<SWSoapService.SWDWebIntegration_Port>, SWSoapService.SWDWebIntegration_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SWDWebIntegration_PortClient() : 
                base(SWDWebIntegration_PortClient.GetDefaultBinding(), SWDWebIntegration_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SWDWebIntegration_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWDWebIntegration_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(SWDWebIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), SWDWebIntegration_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWDWebIntegration_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SWDWebIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWDWebIntegration_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SWDWebIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWDWebIntegration_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnUpdatePurchaseReceiveLine_Result> SWSoapService.SWDWebIntegration_Port.FnUpdatePurchaseReceiveLineAsync(SWSoapService.FnUpdatePurchaseReceiveLine request)
        {
            return base.Channel.FnUpdatePurchaseReceiveLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnUpdatePurchaseReceiveLine_Result> FnUpdatePurchaseReceiveLineAsync(int p_intEntryNo)
        {
            SWSoapService.FnUpdatePurchaseReceiveLine inValue = new SWSoapService.FnUpdatePurchaseReceiveLine();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnUpdatePurchaseReceiveLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnPostPurchaseReceive_Result> SWSoapService.SWDWebIntegration_Port.FnPostPurchaseReceiveAsync(SWSoapService.FnPostPurchaseReceive request)
        {
            return base.Channel.FnPostPurchaseReceiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnPostPurchaseReceive_Result> FnPostPurchaseReceiveAsync(int p_intEntryNo)
        {
            SWSoapService.FnPostPurchaseReceive inValue = new SWSoapService.FnPostPurchaseReceive();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnPostPurchaseReceiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnCreateSalesOrder_Result> SWSoapService.SWDWebIntegration_Port.FnCreateSalesOrderAsync(SWSoapService.FnCreateSalesOrder request)
        {
            return base.Channel.FnCreateSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnCreateSalesOrder_Result> FnCreateSalesOrderAsync(int p_intEntryNo)
        {
            SWSoapService.FnCreateSalesOrder inValue = new SWSoapService.FnCreateSalesOrder();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnCreateSalesOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnPostSalesShipment_Result> SWSoapService.SWDWebIntegration_Port.FnPostSalesShipmentAsync(SWSoapService.FnPostSalesShipment request)
        {
            return base.Channel.FnPostSalesShipmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnPostSalesShipment_Result> FnPostSalesShipmentAsync(int p_intEntryNo)
        {
            SWSoapService.FnPostSalesShipment inValue = new SWSoapService.FnPostSalesShipment();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnPostSalesShipmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnPostSalesInvoice_Result> SWSoapService.SWDWebIntegration_Port.FnPostSalesInvoiceAsync(SWSoapService.FnPostSalesInvoice request)
        {
            return base.Channel.FnPostSalesInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnPostSalesInvoice_Result> FnPostSalesInvoiceAsync(int p_intEntryNo)
        {
            SWSoapService.FnPostSalesInvoice inValue = new SWSoapService.FnPostSalesInvoice();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnPostSalesInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnPostItemJournal_Result> SWSoapService.SWDWebIntegration_Port.FnPostItemJournalAsync(SWSoapService.FnPostItemJournal request)
        {
            return base.Channel.FnPostItemJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnPostItemJournal_Result> FnPostItemJournalAsync(int p_intEntryNo)
        {
            SWSoapService.FnPostItemJournal inValue = new SWSoapService.FnPostItemJournal();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnPostItemJournalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWSoapService.FnPostQCInspection_Result> SWSoapService.SWDWebIntegration_Port.FnPostQCInspectionAsync(SWSoapService.FnPostQCInspection request)
        {
            return base.Channel.FnPostQCInspectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWSoapService.FnPostQCInspection_Result> FnPostQCInspectionAsync(int p_intEntryNo)
        {
            SWSoapService.FnPostQCInspection inValue = new SWSoapService.FnPostQCInspection();
            inValue.p_intEntryNo = p_intEntryNo;
            return ((SWSoapService.SWDWebIntegration_Port)(this)).FnPostQCInspectionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SWDWebIntegration_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SWDWebIntegration_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://vm2012srvweb01.crt-insights.com:3197/DynamicsNAV100_Sunward/WS/SWMY LIVE/C" +
                        "odeunit/SWDWebIntegration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SWDWebIntegration_PortClient.GetBindingForEndpoint(EndpointConfiguration.SWDWebIntegration_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SWDWebIntegration_PortClient.GetEndpointAddress(EndpointConfiguration.SWDWebIntegration_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            SWDWebIntegration_Port,
        }
    }
}
