using Application.Commands;
using Application.Handlers.CommandHandler;
using Application.Response;
using Core.Entities;
using Core.Repositories.Command;
using Core.Repositories.Command.Base;
using Core.Repositories.Query;
using Core.Repositories.Query.Base;
using Infrastructure.Repository.Command;
using Infrastructure.Repository.Command.Base;
using Infrastructure.Repository.Query;
using Infrastructure.Repository.Query.Base;
using Infrastructure.Service;
using MediatR;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddScoped(typeof(IQueryRepository<>), typeof(QueryRepository<>));
            services.AddTransient<IRoleQueryRepository, RoleQueryRepository>();
            services.AddScoped(typeof(ICommandRepository<>), typeof(CommandRepository<>));
            services.AddTransient<IRoleCommandRepository, RoleCommandRepository>();
            services.AddTransient<IEmployeeOtherDutyInformationCommandRepository, EmployeeOtherDutyInformationCommandRepository>();
            //services.AddScoped(typeof(ICommandRepository<ForumTypeResponse>), typeof(CommandRepository<ForumTypeResponse>));

            services.AddScoped(typeof(IRequestHandler<>), typeof(CreateHandler<>));
            services.AddTransient<IPlantQueryRepository, PlantQueryRepository>();
            services.AddTransient<ISoCustomerAddressQueryRepository, SoCustomerAddressQueryRepository>();
            services.AddTransient<IDivisionQueryRepository, DivisionQueryRepository>();
            services.AddTransient<ICodeMasterQueryRepository, CodeMasterQueryRepository>();
            services.AddTransient<IApplicationMasterDetailQueryRepository, ApplicationMasterDetailQueryRepository>();
            services.AddTransient<IDepartmentQueryRepository, DepartmentQueryRepository>();
            services.AddTransient<ISectionQueryRepository, SectionQueryRepository>();
            services.AddTransient<ISubSectionQueryRepository, SubSectionQueryRepository>();
            services.AddTransient<IDesignationQueryRepository, DesignationQueryRepository>();
            services.AddTransient<ILayOutPlanTypeQueryRepository, LayOutPlanTypeQueryRepository>();
            services.AddTransient<IEmployeeQueryRepository, EmployeeQueryRepository>();
            services.AddTransient<IIctmasterQueryRepository, IctmasterQueryRepository>();
            services.AddTransient<IIctmasterCommandRepository, IctmasterCommandRepository>();
            services.AddTransient<IDocumentsQueryRepository, DocumentsQueryRepository>();
            services.AddTransient<IEmployeeOtherDutyInformationQueryRepository, EmployeeOtherDutyInformationQueryRepository>();
            services.AddTransient<IForumCategoryQueryRepository, ForumCategoryQueryRepository>();
            services.AddTransient<ILevelMasterQueryRepository, LevelMasterQueryRepository>();
            services.AddTransient<IForumTypeQueryRepository, ForumTypeQueryRepository>();
            services.AddTransient<IForumTypeCommandRepository, ForumTypeCommandRepository>();
            services.AddTransient<IFourmCategoryCommandRepository, FourmCategoryCommandRepository>();
            services.AddTransient<IForumTopicsQueryRepository, ForumTopicsQueryRepository>();
            services.AddTransient<IEmailTopicsQueryRepository, EmailTopicsQueryRepository>();
            services.AddTransient<IForumConversationsQueryRepository, ForumConversationsQueryRepository>();
            services.AddTransient<IEmailConversationsQueryRepository, EmailConversationsQueryRepository>();
            services.AddTransient<IEmployeeEmailInfoQueryRepository, EmployeeEmailInfoQueryRepository>();
            services.AddTransient<IEmployeeReportTQueryoRepository, EmployeeReportTQueryoRepository>();
            services.AddTransient<IEmployeeEmailInfoForwardQueryRepository, EmployeeEmailInfoForwardQueryRepository>();
            services.AddTransient<IApplicationUserRoleQueryRepository, ApplicationUserRoleQueryRepository>();
            services.AddTransient<IEmployeeEmailInfoAuthorityQueryRepository, EmployeeEmailInfoAuthorityQueryRepository>();
            services.AddTransient<IEmployeeICTInformationQueryRepository, EmployeeICTInformationQueryRepository>();
            services.AddTransient<IEmployeeICTHardInformationQueryRepository, EmployeeICTHardInformationQueryRepository>();
            services.AddTransient<IPlantCommandRepository, PlantCommandRepository>();
            services.AddTransient<IDivisionCommandRepository, DivisionCommandRepository>();
            services.AddTransient<IDepartmentCommandRepository, DepartmentCommandRepository>();
            services.AddTransient<ISubSectionCommandRepository, SubSectionCommandRepository>();
            services.AddTransient<IDesignationCommandRepository, DesignationCommandRepository>();
            services.AddTransient<IEmployeeCommandRepository, EmployeeCommandRepository>();
            services.AddTransient<IApplicationUserCommandRepository, ApplicationUserCommandRepository>();
            services.AddTransient<IApplicationUserQueryRepository, ApplicationUserQueryRepository>();
            services.AddTransient<IApplicationUserRoleCommandRepository, ApplicationUserRoleCommandRepository>();
            services.AddTransient<IEmployeeReportToCommandRepository, EmployeeReportToCommandRepository>();
            services.AddTransient<IEmployeeEmailInfoCommandRepository, EmployeeEmailInfoCommandRepository>();
            services.AddTransient<IEmployeeEmailInfoForwardCommandRepository, EmployeeEmailInfoForwardCommandRepository>();
            services.AddTransient<IEmployeeEmailInfoAuthorityCommandRepository, EmployeeEmailInfoAuthorityCommandRepository>();
            services.AddTransient<IEmployeeICTInformationCommandRepository, EmployeeICTInformationCommandRepository>();
            services.AddTransient<IEmployeeICTHardInformationCommandRepository, EmployeeICTHardInformationCommandRepository>();
            services.AddTransient<IFileUploadCommandRepository, FileUploadCommandRepository>();
            services.AddScoped(typeof(ILocalStorageService<>), typeof(LocalStorageService<>));
            services.AddTransient<IDocumentsCommandRepository, DocumentsCommandRepository>();
            services.AddTransient<ISectionCommandRepository, SectionCommandRepository>();
            services.AddTransient<ILevelMasterCommandRepository, LevelMasterCommandRepository>();
            services.AddTransient<IAppPermissionQueryRepository, AppPermissionQueryRepository>();
            services.AddTransient<IMenuPermissionQueryRepository, MenuPermissionQueryRepository>();
            services.AddTransient<IAppsamplingQueryRepository, AppsamplingQueryRepository>();
            services.AddTransient<IProductionEntryQueryRepository, ProductionEntryQueryRepository>();
            services.AddTransient<IConsumptionQueryRepository, ConsumptionQueryRepository>();
            services.AddTransient<IProductionOutputQueryRepository, ProductionOutputQueryRepository>();
            services.AddTransient<ITopicTodoListQueryRepository, TopicTodoListQueryRepository>();
            services.AddTransient<IRolePermissionQueryRepository, RolePermissionQueryRepository>();
            services.AddTransient<IApplicationPermissionQueryRepository, ApplicationPermissionQueryRepository>();
            services.AddTransient<ISoCustomerQueryRepository, SoCustomerQueryRepository>();
            services.AddTransient<ISoSalesOrderCommandRepository, SoSalesOrderCommandRepository>();
            services.AddTransient<ISoSalesOrderLineCommandRepository, SoSalesOrderLineCommandRepository>();
            services.AddTransient<IPostSalesOrderCommandRepository, PostSalesOrderCommandRepository>();
            services.AddTransient<ISoSalesOrderQueryRepository, SoSalesOrderQueryRepository>();
            services.AddTransient<ISoSalesOrderLineQueryRepository, SoSalesOrderLineQueryRepository>();
            services.AddTransient<IPostSalesOrderQueryRepository, PostSalesOrderQueryRepository>();
            services.AddTransient<IFileStorageService, FileStorageService>();
            services.AddTransient<IApplicationMasterChildQueryRepository, ApplicationMasterChildQueryRepository>();
            services.AddTransient<IAssetCatalogMasterQueryRepository, AssetCatalogMasterQueryRepository>();
            services.AddTransient<IAssetCatalogMasterCommandRepository, AssetCatalogMasterCommandRepository>();
            services.AddTransient<IAssetPartsMaintenaceMasterQueryRepository, AssetPartsMaintenaceMasterQueryRepository>();
            services.AddTransient<IAssetPartsMaintenaceMasterCommandRepository, AssetPartsMaintenaceMasterCommandRepository>();
            services.AddTransient<IAssetEquipmentMaintenaceMasterQueryRepository, AssetEquipmentMaintenaceMasterQueryRepository>();
            services.AddTransient<IAssetEquipmentMaintenaceMasterCommandRepository, AssetEquipmentMaintenaceMasterCommandRepository>();
            services.AddTransient<IAssetEquipmentMaintenaceMasterAssetDocumentCommandRepository, AssetEquipmentMaintenaceMasterAssetDocumentCommandRepository>();
            services.AddTransient<IAssetEquipmentMaintenaceMasterAssetDocumentQueryRepository, AssetEquipmentMaintenaceMasterAssetDocumentQueryRepository>();
            services.AddTransient<INavItemsQueryRepository, NavItemsQueryRepository>();
            services.AddTransient<INavItemsCommandRepository, NavItemsCommandRepository>();
            services.AddTransient<IApplicationMasterDetailCommandRepository, ApplicationMasterDetailCommandRepository>();
            services.AddTransient<IApplicationMasterParentQueryRepository, ApplicationMasterParentQueryRepository>();
            services.AddTransient<IApplicationMasterChildCommandRepository, ApplicationMasterChildCommandRepository>();
            services.AddTransient<ISalesOrderMasterPricingQueryRepository, SalesOrderMasterPricingQueryRepository>();
            services.AddTransient<ISalesOrderMasterPricingLineQueryRepository, SalesOrderMasterPricingLineQueryRepository>();
            services.AddTransient<ISalesOrderMasterPricingLineSellingMethodQueryRepository, SalesOrderMasterPricingLineSellingMethodQueryRepository>();
            services.AddTransient<ISalesOrderMasterPricingCommandRepository, SalesOrderMasterPricingCommandRepository>();
            services.AddTransient<ISalesOrderMasterPricingLineCommandRepository, SalesOrderMasterPricingLineCommandRepository>();
            services.AddTransient<ISalesOrderMasterPricingLineSellingMethodCommandRepository, SalesOrderMasterPricingLineSellingMethodCommandRepository>();
            services.AddTransient<IProductionActivityAppLineReportQueryRepository, ProductionActivityAppLineReportQueryRepository>();
            services.AddTransient<IFmGlobalQueryRepository, FmGlobalQueryRepository>();
            services.AddTransient<IFmGlobalLineQueryRepository, FmGlobalLineQueryRepository>();
            services.AddTransient<IFmGlobalLineItemQueryRepository, FmGlobalLineItemQueryRepository>();
            services.AddTransient<ISalesOrderService, SalesOrderService>();
            services.AddTransient<IFmGlobalCommandRepository, FmGlobalCommandRepository>();
            services.AddTransient<IFmGlobalLineCommandRepository, FmGlobalLineCommandRepository>();
            services.AddTransient<IFmGlobalLineItemCommandRepository, FmGlobalLineItemCommandRepository>();
            services.AddTransient<ISoCustomerCommandRepository, SoCustomerCommandRepository>();

            services.AddTransient<INavProductionInformationCommandRepository, NavProductionInformationCommandRepository>();
            services.AddTransient<INavCrossReferenceCommandRepository, NavCrossReferenceCommandRepository>();
            services.AddTransient<IReportFileUploadsQueryRepository, ReportFileUploadsQueryRepository>();
            services.AddTransient<IEmailActivityCatgorysQueryRepository,EmailActivityCatgorysQueryRepository>();
            services.AddTransient<IToDoNotesQueryRepository, ToDoNotesQueryRepository>();
            services.AddTransient<IToDoNotesHistoryQueryRepository, ToDoNotesHistoryQueryRepository>();
            services.AddTransient<IDashboardQueryRepository, DashboardQueryRepository>();
            services.AddTransient<IFileProfileTypeDocumentQueryRepository, FileProfileTypeDocumentQueryRepository>();

            services.AddTransient<IFmGlobalMoveCommandRepository, FmGlobalMoveCommandRepository>();
            services.AddTransient<IFileprofileQueryRepository,FileprofiletypeQueryRepository>();
            services.AddTransient<INewEmailUploadQueryRepository, NewEmailUploadQueryRepository>();
            services.AddTransient<ICreateEmailTopicEditQueryRepository, CreateEmailTopicEditQueryRepository>();
            services.AddTransient<ICCDFImplementationQueryRepository,CCFDImplementationQueryRepository>();
            return services;
        }
    }
}
