using Application.Commands;
using Application.Handlers.CommandHandler;
using Application.Response;
using Core.Entities;
using Core.Repositories.Command;
using Core.Repositories.Command.Base;
using Core.Repositories.Query;
using Core.Repositories.Query.Base;
using Infrastructure.Repository.Command;
using Infrastructure.Repository.Command.Base;
using Infrastructure.Repository.Query;
using Infrastructure.Repository.Query.Base;
using Infrastructure.Service;
using MediatR;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddScoped(typeof(IQueryRepository<>), typeof(QueryRepository<>));
            services.AddScoped<IRoleQueryRepository, RoleQueryRepository>();
            services.AddScoped(typeof(ICommandRepository<>), typeof(CommandRepository<>));
            services.AddScoped<IRoleCommandRepository, RoleCommandRepository>();
            services.AddScoped<IEmployeeOtherDutyInformationCommandRepository, EmployeeOtherDutyInformationCommandRepository>();
            //services.AddScoped(typeof(ICommandRepository<ForumTypeResponse>), typeof(CommandRepository<ForumTypeResponse>));

            services.AddScoped(typeof(IRequestHandler<>), typeof(CreateHandler<>));
            services.AddScoped<IPlantQueryRepository, PlantQueryRepository>();
            services.AddScoped<ISoCustomerAddressQueryRepository, SoCustomerAddressQueryRepository>();
            services.AddScoped<IDivisionQueryRepository, DivisionQueryRepository>();
            services.AddScoped<ICodeMasterQueryRepository, CodeMasterQueryRepository>();
            services.AddScoped<IApplicationMasterDetailQueryRepository, ApplicationMasterDetailQueryRepository>();
            services.AddScoped<IDepartmentQueryRepository, DepartmentQueryRepository>();
            services.AddScoped<ISectionQueryRepository, SectionQueryRepository>();
            services.AddScoped<ISubSectionQueryRepository, SubSectionQueryRepository>();
            services.AddScoped<IDesignationQueryRepository, DesignationQueryRepository>();
            services.AddScoped<ILayOutPlanTypeQueryRepository, LayOutPlanTypeQueryRepository>();
            services.AddScoped<IEmployeeQueryRepository, EmployeeQueryRepository>();
            services.AddScoped<IIctmasterQueryRepository, IctmasterQueryRepository>();
            services.AddScoped<IIctmasterCommandRepository, IctmasterCommandRepository>();
            services.AddScoped<IDocumentsQueryRepository, DocumentsQueryRepository>();
            services.AddScoped<IEmployeeOtherDutyInformationQueryRepository, EmployeeOtherDutyInformationQueryRepository>();
            services.AddScoped<IForumCategoryQueryRepository, ForumCategoryQueryRepository>();
            services.AddScoped<ILevelMasterQueryRepository, LevelMasterQueryRepository>();
            services.AddScoped<IForumTypeQueryRepository, ForumTypeQueryRepository>();
            services.AddScoped<IForumTypeCommandRepository, ForumTypeCommandRepository>();
            services.AddScoped<IFourmCategoryCommandRepository, FourmCategoryCommandRepository>();
            services.AddScoped<IForumTopicsQueryRepository, ForumTopicsQueryRepository>();
            services.AddScoped<IEmailTopicsQueryRepository, EmailTopicsQueryRepository>();
            services.AddScoped<IForumConversationsQueryRepository, ForumConversationsQueryRepository>();
            services.AddScoped<IEmailConversationsQueryRepository, EmailConversationsQueryRepository>();
            services.AddScoped<IEmployeeEmailInfoQueryRepository, EmployeeEmailInfoQueryRepository>();
            services.AddScoped<IEmployeeReportTQueryoRepository, EmployeeReportTQueryoRepository>();
            services.AddScoped<IEmployeeEmailInfoForwardQueryRepository, EmployeeEmailInfoForwardQueryRepository>();
            services.AddScoped<IApplicationUserRoleQueryRepository, ApplicationUserRoleQueryRepository>();
            services.AddScoped<IEmployeeEmailInfoAuthorityQueryRepository, EmployeeEmailInfoAuthorityQueryRepository>();
            services.AddScoped<IEmployeeICTInformationQueryRepository, EmployeeICTInformationQueryRepository>();
            services.AddScoped<IEmployeeICTHardInformationQueryRepository, EmployeeICTHardInformationQueryRepository>();
            services.AddScoped<IPlantCommandRepository, PlantCommandRepository>();
            services.AddScoped<IDivisionCommandRepository, DivisionCommandRepository>();
            services.AddScoped<IDepartmentCommandRepository, DepartmentCommandRepository>();
            services.AddScoped<ISubSectionCommandRepository, SubSectionCommandRepository>();
            services.AddScoped<IDesignationCommandRepository, DesignationCommandRepository>();
            services.AddScoped<IEmployeeCommandRepository, EmployeeCommandRepository>();
            services.AddScoped<IApplicationUserCommandRepository, ApplicationUserCommandRepository>();
            services.AddScoped<IApplicationUserQueryRepository, ApplicationUserQueryRepository>();
            services.AddScoped<IApplicationUserRoleCommandRepository, ApplicationUserRoleCommandRepository>();
            services.AddScoped<IEmployeeReportToCommandRepository, EmployeeReportToCommandRepository>();
            services.AddScoped<IEmployeeEmailInfoCommandRepository, EmployeeEmailInfoCommandRepository>();
            services.AddScoped<IEmployeeEmailInfoForwardCommandRepository, EmployeeEmailInfoForwardCommandRepository>();
            services.AddScoped<IEmployeeEmailInfoAuthorityCommandRepository, EmployeeEmailInfoAuthorityCommandRepository>();
            services.AddScoped<IEmployeeICTInformationCommandRepository, EmployeeICTInformationCommandRepository>();
            services.AddScoped<IEmployeeICTHardInformationCommandRepository, EmployeeICTHardInformationCommandRepository>();
            services.AddScoped<IFileUploadCommandRepository, FileUploadCommandRepository>();
            services.AddScoped(typeof(ILocalStorageService<>), typeof(LocalStorageService<>));
            services.AddScoped<IDocumentsCommandRepository, DocumentsCommandRepository>();
            services.AddScoped<ISectionCommandRepository, SectionCommandRepository>();
            services.AddScoped<ILevelMasterCommandRepository, LevelMasterCommandRepository>();
            services.AddScoped<IAppPermissionQueryRepository, AppPermissionQueryRepository>();
            services.AddScoped<IMenuPermissionQueryRepository, MenuPermissionQueryRepository>();
            services.AddScoped<IAppsamplingQueryRepository, AppsamplingQueryRepository>();
            services.AddScoped<IProductionEntryQueryRepository, ProductionEntryQueryRepository>();
            services.AddScoped<IConsumptionQueryRepository, ConsumptionQueryRepository>();
            services.AddScoped<IProductionOutputQueryRepository, ProductionOutputQueryRepository>();
            services.AddScoped<ITopicTodoListQueryRepository, TopicTodoListQueryRepository>();
            services.AddScoped<IRolePermissionQueryRepository, RolePermissionQueryRepository>();
            services.AddScoped<IApplicationPermissionQueryRepository, ApplicationPermissionQueryRepository>();
            services.AddScoped<ISoCustomerQueryRepository, SoCustomerQueryRepository>();
            services.AddScoped<ISoSalesOrderCommandRepository, SoSalesOrderCommandRepository>();
            services.AddScoped<ISoSalesOrderLineCommandRepository, SoSalesOrderLineCommandRepository>();
            services.AddScoped<IPostSalesOrderCommandRepository, PostSalesOrderCommandRepository>();
            services.AddScoped<ISoSalesOrderQueryRepository, SoSalesOrderQueryRepository>();
            services.AddScoped<ISoSalesOrderLineQueryRepository, SoSalesOrderLineQueryRepository>();
            services.AddScoped<IPostSalesOrderQueryRepository, PostSalesOrderQueryRepository>();
            services.AddScoped<IFileStorageService, FileStorageService>();
            services.AddScoped<IApplicationMasterChildQueryRepository, ApplicationMasterChildQueryRepository>();
            services.AddScoped<IAssetCatalogMasterQueryRepository, AssetCatalogMasterQueryRepository>();
            services.AddScoped<IAssetCatalogMasterCommandRepository, AssetCatalogMasterCommandRepository>();
            services.AddScoped<IAssetPartsMaintenaceMasterQueryRepository, AssetPartsMaintenaceMasterQueryRepository>();
            services.AddScoped<IAssetPartsMaintenaceMasterCommandRepository, AssetPartsMaintenaceMasterCommandRepository>();
            services.AddScoped<IAssetEquipmentMaintenaceMasterQueryRepository, AssetEquipmentMaintenaceMasterQueryRepository>();
            services.AddScoped<IAssetEquipmentMaintenaceMasterCommandRepository, AssetEquipmentMaintenaceMasterCommandRepository>();
            services.AddScoped<IAssetEquipmentMaintenaceMasterAssetDocumentCommandRepository, AssetEquipmentMaintenaceMasterAssetDocumentCommandRepository>();
            services.AddScoped<IAssetEquipmentMaintenaceMasterAssetDocumentQueryRepository, AssetEquipmentMaintenaceMasterAssetDocumentQueryRepository>();
            services.AddScoped<INavItemsQueryRepository, NavItemsQueryRepository>();
            services.AddScoped<INavItemsCommandRepository, NavItemsCommandRepository>();
            services.AddScoped<IApplicationMasterDetailCommandRepository, ApplicationMasterDetailCommandRepository>();
            services.AddScoped<IApplicationMasterParentQueryRepository, ApplicationMasterParentQueryRepository>();
            services.AddScoped<IApplicationMasterChildCommandRepository, ApplicationMasterChildCommandRepository>();
            services.AddScoped<ISalesOrderMasterPricingQueryRepository, SalesOrderMasterPricingQueryRepository>();
            services.AddScoped<ISalesOrderMasterPricingLineQueryRepository, SalesOrderMasterPricingLineQueryRepository>();
            services.AddScoped<ISalesOrderMasterPricingLineSellingMethodQueryRepository, SalesOrderMasterPricingLineSellingMethodQueryRepository>();
            services.AddScoped<ISalesOrderMasterPricingCommandRepository, SalesOrderMasterPricingCommandRepository>();
            services.AddScoped<ISalesOrderMasterPricingLineCommandRepository, SalesOrderMasterPricingLineCommandRepository>();
            services.AddScoped<ISalesOrderMasterPricingLineSellingMethodCommandRepository, SalesOrderMasterPricingLineSellingMethodCommandRepository>();
            services.AddScoped<IProductionActivityAppLineReportQueryRepository, ProductionActivityAppLineReportQueryRepository>();
            services.AddScoped<IFmGlobalQueryRepository, FmGlobalQueryRepository>();
            services.AddScoped<IFmGlobalLineQueryRepository, FmGlobalLineQueryRepository>();
            services.AddScoped<IFmGlobalLineItemQueryRepository, FmGlobalLineItemQueryRepository>();
            services.AddScoped<ISalesOrderService, SalesOrderService>();
            services.AddScoped<IFmGlobalCommandRepository, FmGlobalCommandRepository>();
            services.AddScoped<IFmGlobalLineCommandRepository, FmGlobalLineCommandRepository>();
            services.AddScoped<IFmGlobalLineItemCommandRepository, FmGlobalLineItemCommandRepository>();
            services.AddScoped<ISoCustomerCommandRepository, SoCustomerCommandRepository>();
            services.AddScoped<IAttributeHeaderCommandRepository, AttributeHeaderCommandRepository>();
            services.AddScoped<IAttributeQueryRepository, AttributeHeaderQueryRepository>();

            services.AddScoped<INavProductionInformationCommandRepository, NavProductionInformationCommandRepository>();
            services.AddScoped<INavCrossReferenceCommandRepository, NavCrossReferenceCommandRepository>();
            services.AddScoped<IReportFileUploadsQueryRepository, ReportFileUploadsQueryRepository>();
            services.AddScoped<IEmailActivityCatgorysQueryRepository,EmailActivityCatgorysQueryRepository>();
            services.AddScoped<IToDoNotesQueryRepository, ToDoNotesQueryRepository>();
            services.AddScoped<IToDoNotesHistoryQueryRepository, ToDoNotesHistoryQueryRepository>();
            services.AddScoped<IDashboardQueryRepository, DashboardQueryRepository>();

            services.AddScoped<IFmGlobalMoveCommandRepository, FmGlobalMoveCommandRepository>();
            services.AddScoped<IFileprofileQueryRepository,FileprofiletypeQueryRepository>();
            services.AddScoped<INewEmailUploadQueryRepository, NewEmailUploadQueryRepository>();
            services.AddScoped<ICreateEmailTopicEditQueryRepository, CreateEmailTopicEditQueryRepository>();
            services.AddScoped<ICCDFImplementationQueryRepository,CCFDImplementationQueryRepository>();
            services.AddScoped<IChangeControlFormQueryRepository, ChangeControlFormQueryRepository>();
            services.AddScoped<IGenerateDocumentNoSeriesQueryRepository, GenerateDocumentNoSeriesQueryRepository>();
            services.AddScoped<IGenerateDocumentNoSeriesSeviceQueryRepository, GenerateDocumentNoSeriesService>();
            
            services.AddScoped<IAttributeDetailsCommandRepository, AttributeDetailsCommandRepository>();
            services.AddScoped<IAttributeDetailsQueryRepository, AttributeDetailsQueryRepository>();
            services.AddScoped<IDynamicFormQueryRepository, DynamicFormQueryRepository>();
            services.AddScoped<IRoutineQueryRepository, RoutineQueryRepository>();
            services.AddScoped<ITransferPermissionsQueryRepository, TransferPermissionsQueryRepository>();
            services.AddScoped<IProductionActivityQueryRepository,ProductionActivityAppLineQueryRepository>();
            services.AddScoped<IProductionActivityAppQueryRepository,ProductionActivityAppQueryRepository>();
            services.AddScoped<IRoutineLineAppQuery, RoutineAppLineQueryRepository>();
            services.AddScoped<ISettingsQueryRepository, SettingsQueryRepository>();
            services.AddScoped<IDynamicFormDataSourceQueryRepository, DynamicFormDataSourceQueryRepository>();
            services.AddScoped<IQuotationHistoryQueryRepository, QuotationHistoryQueryRepository>();
            services.AddScoped<ITempSalesPackInformationQueryRepository, TempSalesPackInformationQueryRepository>();
            services.AddScoped<IUserGroupQueryRepository, UserGroupQueryRepository>();
            services.AddScoped<IIpirAppQueryRepostitory, IpirAppQueryRepostitory>();
            services.AddScoped<IFbOutputCartonsQueryRepository, FbOutputCartonsQueryRepository>();
            services.AddScoped<IDistStockBalanceQueryRepository, DistStockBalanceQueryRepository>();
            services.AddScoped<IProductionSimulationQueryRepository,ProductionSimulationCommandRepository>();
            return services;
        }
    }
}
